---
- name: Run the new module
  my_test:
    name: 'hello'
    new: true
  register: testout
- name: Dump test output
  ansible.builtin.debug:
    msg: '{{ testout }}'

- name: Get the login user
  ansible.builtin.debug:
    msg: '{{ ansible_env["USER"] }}'
  register: login_user

- name: Run the User info module
  user_info:
    username: '{{ login_user.msg }}'
  register: user_info_output
- name: Dump User output
  ansible.builtin.debug:
    msg: '{{ user_info_output }}'
