---
- name: Run the new module
  my_test:
    name: 'hello'
    new: true
  register: testout
- name: Dump test output
  ansible.builtin.debug:
    msg: '{{ testout }}'

- name: Run the User info module
  user_info:
    username: 'vscode'
  register: user_info_output
- name: Dump User output
  ansible.builtin.debug:
    msg: '{{ user_info_output }}'
